package com.queue.mapper;

import com.queue.entity.CurrencyTbl;

public interface CurrencyTblMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_tbl
     *
     * @mbg.generated
     */
    int insert(CurrencyTbl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table currency_tbl
     *
     * @mbg.generated
     */
    int insertSelective(CurrencyTbl record);
}