package com.queue.mapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.queue.entity.ExchangeRate;

import java.util.List;

public interface ExchangeRateMapper extends BaseMapper<ExchangeRate> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exchange_rate
     *
     * @mbg.generated
     */
    int insertSelective(ExchangeRate record);

    List<ExchangeRate> searchExchangeByPage();
}