package com.queue.mapper;

import com.queue.entity.OtherDayWeather;

public interface OtherDayWeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_day_weather
     *
     * @mbg.generated
     */
    int insert(OtherDayWeather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_day_weather
     *
     * @mbg.generated
     */
    int insertSelective(OtherDayWeather record);
}