package com.queue.mapper;

import com.queue.entity.RoleInf;

public interface RoleInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_inf
     *
     * @mbg.generated
     */
    int insert(RoleInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_inf
     *
     * @mbg.generated
     */
    int insertSelective(RoleInf record);
}