package com.queue.mapper;

import com.queue.entity.TedayWeather;

public interface TedayWeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teday_weather
     *
     * @mbg.generated
     */
    int insert(TedayWeather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teday_weather
     *
     * @mbg.generated
     */
    int insertSelective(TedayWeather record);
}