package com.queue.mapper;

import com.queue.entity.WeatherCity;

public interface WeatherCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEATHER_CITY
     *
     * @mbg.generated
     */
    int insert(WeatherCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WEATHER_CITY
     *
     * @mbg.generated
     */
    int insertSelective(WeatherCity record);
}