package com.queue.entity;

import java.io.Serializable;

public class CurrencyTbl implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_tbl.C_ID
     *
     * @mbg.generated
     */
    private Long cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_tbl.CUR_ID
     *
     * @mbg.generated
     */
    private String curId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_tbl.CUR_NAME
     *
     * @mbg.generated
     */
    private String curName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_tbl.CUR_STATUS
     *
     * @mbg.generated
     */
    private Short curStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column currency_tbl.DEL_STATUS
     *
     * @mbg.generated
     */
    private Short delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table currency_tbl
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_tbl.C_ID
     *
     * @return the value of currency_tbl.C_ID
     *
     * @mbg.generated
     */
    public Long getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_tbl.C_ID
     *
     * @param cId the value for currency_tbl.C_ID
     *
     * @mbg.generated
     */
    public void setcId(Long cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_tbl.CUR_ID
     *
     * @return the value of currency_tbl.CUR_ID
     *
     * @mbg.generated
     */
    public String getCurId() {
        return curId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_tbl.CUR_ID
     *
     * @param curId the value for currency_tbl.CUR_ID
     *
     * @mbg.generated
     */
    public void setCurId(String curId) {
        this.curId = curId == null ? null : curId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_tbl.CUR_NAME
     *
     * @return the value of currency_tbl.CUR_NAME
     *
     * @mbg.generated
     */
    public String getCurName() {
        return curName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_tbl.CUR_NAME
     *
     * @param curName the value for currency_tbl.CUR_NAME
     *
     * @mbg.generated
     */
    public void setCurName(String curName) {
        this.curName = curName == null ? null : curName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_tbl.CUR_STATUS
     *
     * @return the value of currency_tbl.CUR_STATUS
     *
     * @mbg.generated
     */
    public Short getCurStatus() {
        return curStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_tbl.CUR_STATUS
     *
     * @param curStatus the value for currency_tbl.CUR_STATUS
     *
     * @mbg.generated
     */
    public void setCurStatus(Short curStatus) {
        this.curStatus = curStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column currency_tbl.DEL_STATUS
     *
     * @return the value of currency_tbl.DEL_STATUS
     *
     * @mbg.generated
     */
    public Short getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column currency_tbl.DEL_STATUS
     *
     * @param delStatus the value for currency_tbl.DEL_STATUS
     *
     * @mbg.generated
     */
    public void setDelStatus(Short delStatus) {
        this.delStatus = delStatus;
    }
}