package com.queue.entity;

import com.baomidou.mybatisplus.activerecord.Model;

import java.io.Serializable;
import java.util.Date;

public class ExchangeRate extends Model<ExchangeRate> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.EXC_ID
     *
     * @mbg.generated
     */
    private Long excId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.CONVERT_FRONT_NAME
     *
     * @mbg.generated
     */
    private String convertFrontName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.CONVERT_FRONT_NUM
     *
     * @mbg.generated
     */
    private Double convertFrontNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.CONVERT_LATER_NAME
     *
     * @mbg.generated
     */
    private String convertLaterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.CONVERT_LATER_NUM
     *
     * @mbg.generated
     */
    private Double convertLaterNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.SEARCH_TYPE
     *
     * @mbg.generated
     */
    private String searchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.FRAUD_FRONT_NAME
     *
     * @mbg.generated
     */
    private String fraudFrontName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.FRAUD_FRONT_NUM
     *
     * @mbg.generated
     */
    private Double fraudFrontNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.FRAUD_LATER_NAME
     *
     * @mbg.generated
     */
    private String fraudLaterName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.FRAUD_LATER_NUM
     *
     * @mbg.generated
     */
    private Double fraudLaterNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_rate.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exchange_rate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.EXC_ID
     *
     * @return the value of exchange_rate.EXC_ID
     *
     * @mbg.generated
     */
    public Long getExcId() {
        return excId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.EXC_ID
     *
     * @param excId the value for exchange_rate.EXC_ID
     *
     * @mbg.generated
     */
    public void setExcId(Long excId) {
        this.excId = excId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.CONVERT_FRONT_NAME
     *
     * @return the value of exchange_rate.CONVERT_FRONT_NAME
     *
     * @mbg.generated
     */
    public String getConvertFrontName() {
        return convertFrontName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.CONVERT_FRONT_NAME
     *
     * @param convertFrontName the value for exchange_rate.CONVERT_FRONT_NAME
     *
     * @mbg.generated
     */
    public void setConvertFrontName(String convertFrontName) {
        this.convertFrontName = convertFrontName == null ? null : convertFrontName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.CONVERT_FRONT_NUM
     *
     * @return the value of exchange_rate.CONVERT_FRONT_NUM
     *
     * @mbg.generated
     */
    public Double getConvertFrontNum() {
        return convertFrontNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.CONVERT_FRONT_NUM
     *
     * @param convertFrontNum the value for exchange_rate.CONVERT_FRONT_NUM
     *
     * @mbg.generated
     */
    public void setConvertFrontNum(Double convertFrontNum) {
        this.convertFrontNum = convertFrontNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.CONVERT_LATER_NAME
     *
     * @return the value of exchange_rate.CONVERT_LATER_NAME
     *
     * @mbg.generated
     */
    public String getConvertLaterName() {
        return convertLaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.CONVERT_LATER_NAME
     *
     * @param convertLaterName the value for exchange_rate.CONVERT_LATER_NAME
     *
     * @mbg.generated
     */
    public void setConvertLaterName(String convertLaterName) {
        this.convertLaterName = convertLaterName == null ? null : convertLaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.CONVERT_LATER_NUM
     *
     * @return the value of exchange_rate.CONVERT_LATER_NUM
     *
     * @mbg.generated
     */
    public Double getConvertLaterNum() {
        return convertLaterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.CONVERT_LATER_NUM
     *
     * @param convertLaterNum the value for exchange_rate.CONVERT_LATER_NUM
     *
     * @mbg.generated
     */
    public void setConvertLaterNum(Double convertLaterNum) {
        this.convertLaterNum = convertLaterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.SEARCH_TYPE
     *
     * @return the value of exchange_rate.SEARCH_TYPE
     *
     * @mbg.generated
     */
    public String getSearchType() {
        return searchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.SEARCH_TYPE
     *
     * @param searchType the value for exchange_rate.SEARCH_TYPE
     *
     * @mbg.generated
     */
    public void setSearchType(String searchType) {
        this.searchType = searchType == null ? null : searchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.FRAUD_FRONT_NAME
     *
     * @return the value of exchange_rate.FRAUD_FRONT_NAME
     *
     * @mbg.generated
     */
    public String getFraudFrontName() {
        return fraudFrontName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.FRAUD_FRONT_NAME
     *
     * @param fraudFrontName the value for exchange_rate.FRAUD_FRONT_NAME
     *
     * @mbg.generated
     */
    public void setFraudFrontName(String fraudFrontName) {
        this.fraudFrontName = fraudFrontName == null ? null : fraudFrontName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.FRAUD_FRONT_NUM
     *
     * @return the value of exchange_rate.FRAUD_FRONT_NUM
     *
     * @mbg.generated
     */
    public Double getFraudFrontNum() {
        return fraudFrontNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.FRAUD_FRONT_NUM
     *
     * @param fraudFrontNum the value for exchange_rate.FRAUD_FRONT_NUM
     *
     * @mbg.generated
     */
    public void setFraudFrontNum(Double fraudFrontNum) {
        this.fraudFrontNum = fraudFrontNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.FRAUD_LATER_NAME
     *
     * @return the value of exchange_rate.FRAUD_LATER_NAME
     *
     * @mbg.generated
     */
    public String getFraudLaterName() {
        return fraudLaterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.FRAUD_LATER_NAME
     *
     * @param fraudLaterName the value for exchange_rate.FRAUD_LATER_NAME
     *
     * @mbg.generated
     */
    public void setFraudLaterName(String fraudLaterName) {
        this.fraudLaterName = fraudLaterName == null ? null : fraudLaterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.FRAUD_LATER_NUM
     *
     * @return the value of exchange_rate.FRAUD_LATER_NUM
     *
     * @mbg.generated
     */
    public Double getFraudLaterNum() {
        return fraudLaterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.FRAUD_LATER_NUM
     *
     * @param fraudLaterNum the value for exchange_rate.FRAUD_LATER_NUM
     *
     * @mbg.generated
     */
    public void setFraudLaterNum(Double fraudLaterNum) {
        this.fraudLaterNum = fraudLaterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exchange_rate.CREATE_TIME
     *
     * @return the value of exchange_rate.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exchange_rate.CREATE_TIME
     *
     * @param createTime the value for exchange_rate.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    protected Serializable pkVal(){ return this.excId; }
}