package com.queue.entity;

import java.io.Serializable;
import java.util.Date;

public class OtherDayWeather implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.ODW_ID
     *
     * @mbg.generated
     */
    private Long odwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    private String tIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.ODW_DAY
     *
     * @mbg.generated
     */
    private String odwDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.ODW_WEATHER
     *
     * @mbg.generated
     */
    private String odwWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    private String windDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.ODW_WEEK
     *
     * @mbg.generated
     */
    private String odwWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column other_day_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table other_day_weather
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.ODW_ID
     *
     * @return the value of other_day_weather.ODW_ID
     *
     * @mbg.generated
     */
    public Long getOdwId() {
        return odwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.ODW_ID
     *
     * @param odwId the value for other_day_weather.ODW_ID
     *
     * @mbg.generated
     */
    public void setOdwId(Long odwId) {
        this.odwId = odwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.T_IDENTITY
     *
     * @return the value of other_day_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    public String gettIdentity() {
        return tIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.T_IDENTITY
     *
     * @param tIdentity the value for other_day_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    public void settIdentity(String tIdentity) {
        this.tIdentity = tIdentity == null ? null : tIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.ODW_DAY
     *
     * @return the value of other_day_weather.ODW_DAY
     *
     * @mbg.generated
     */
    public String getOdwDay() {
        return odwDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.ODW_DAY
     *
     * @param odwDay the value for other_day_weather.ODW_DAY
     *
     * @mbg.generated
     */
    public void setOdwDay(String odwDay) {
        this.odwDay = odwDay == null ? null : odwDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.TEMPERATURE
     *
     * @return the value of other_day_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.TEMPERATURE
     *
     * @param temperature the value for other_day_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.ODW_WEATHER
     *
     * @return the value of other_day_weather.ODW_WEATHER
     *
     * @mbg.generated
     */
    public String getOdwWeather() {
        return odwWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.ODW_WEATHER
     *
     * @param odwWeather the value for other_day_weather.ODW_WEATHER
     *
     * @mbg.generated
     */
    public void setOdwWeather(String odwWeather) {
        this.odwWeather = odwWeather == null ? null : odwWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.WIND_DIRECTION
     *
     * @return the value of other_day_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    public String getWindDirection() {
        return windDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.WIND_DIRECTION
     *
     * @param windDirection the value for other_day_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    public void setWindDirection(String windDirection) {
        this.windDirection = windDirection == null ? null : windDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.ODW_WEEK
     *
     * @return the value of other_day_weather.ODW_WEEK
     *
     * @mbg.generated
     */
    public String getOdwWeek() {
        return odwWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.ODW_WEEK
     *
     * @param odwWeek the value for other_day_weather.ODW_WEEK
     *
     * @mbg.generated
     */
    public void setOdwWeek(String odwWeek) {
        this.odwWeek = odwWeek == null ? null : odwWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column other_day_weather.CREATE_TIME
     *
     * @return the value of other_day_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column other_day_weather.CREATE_TIME
     *
     * @param createTime the value for other_day_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}