package com.queue.entity;

import java.io.Serializable;
import java.util.Date;

public class Permissions implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.pms_id
     *
     * @mbg.generated
     */
    private Short pmsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.pms_code
     *
     * @mbg.generated
     */
    private String pmsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.pms_name
     *
     * @mbg.generated
     */
    private String pmsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.pms_url
     *
     * @mbg.generated
     */
    private String pmsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.reviser
     *
     * @mbg.generated
     */
    private String reviser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.describe_inf
     *
     * @mbg.generated
     */
    private String describeInf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permissions
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.pms_id
     *
     * @return the value of permissions.pms_id
     *
     * @mbg.generated
     */
    public Short getPmsId() {
        return pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.pms_id
     *
     * @param pmsId the value for permissions.pms_id
     *
     * @mbg.generated
     */
    public void setPmsId(Short pmsId) {
        this.pmsId = pmsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.pms_code
     *
     * @return the value of permissions.pms_code
     *
     * @mbg.generated
     */
    public String getPmsCode() {
        return pmsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.pms_code
     *
     * @param pmsCode the value for permissions.pms_code
     *
     * @mbg.generated
     */
    public void setPmsCode(String pmsCode) {
        this.pmsCode = pmsCode == null ? null : pmsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.pms_name
     *
     * @return the value of permissions.pms_name
     *
     * @mbg.generated
     */
    public String getPmsName() {
        return pmsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.pms_name
     *
     * @param pmsName the value for permissions.pms_name
     *
     * @mbg.generated
     */
    public void setPmsName(String pmsName) {
        this.pmsName = pmsName == null ? null : pmsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.pms_url
     *
     * @return the value of permissions.pms_url
     *
     * @mbg.generated
     */
    public String getPmsUrl() {
        return pmsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.pms_url
     *
     * @param pmsUrl the value for permissions.pms_url
     *
     * @mbg.generated
     */
    public void setPmsUrl(String pmsUrl) {
        this.pmsUrl = pmsUrl == null ? null : pmsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.create_time
     *
     * @return the value of permissions.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.create_time
     *
     * @param createTime the value for permissions.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.creator
     *
     * @return the value of permissions.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.creator
     *
     * @param creator the value for permissions.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.update_time
     *
     * @return the value of permissions.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.update_time
     *
     * @param updateTime the value for permissions.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.reviser
     *
     * @return the value of permissions.reviser
     *
     * @mbg.generated
     */
    public String getReviser() {
        return reviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.reviser
     *
     * @param reviser the value for permissions.reviser
     *
     * @mbg.generated
     */
    public void setReviser(String reviser) {
        this.reviser = reviser == null ? null : reviser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.is_delete
     *
     * @return the value of permissions.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.is_delete
     *
     * @param isDelete the value for permissions.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.describe_inf
     *
     * @return the value of permissions.describe_inf
     *
     * @mbg.generated
     */
    public String getDescribeInf() {
        return describeInf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.describe_inf
     *
     * @param describeInf the value for permissions.describe_inf
     *
     * @mbg.generated
     */
    public void setDescribeInf(String describeInf) {
        this.describeInf = describeInf == null ? null : describeInf.trim();
    }
}