package com.queue.entity;

import java.io.Serializable;
import java.util.Date;

public class RoleInf implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.role_id
     *
     * @mbg.generated
     */
    private Short roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.role_code
     *
     * @mbg.generated
     */
    private String roleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.reviser
     *
     * @mbg.generated
     */
    private String reviser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_inf.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table role_inf
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.role_id
     *
     * @return the value of role_inf.role_id
     *
     * @mbg.generated
     */
    public Short getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.role_id
     *
     * @param roleId the value for role_inf.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Short roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.role_code
     *
     * @return the value of role_inf.role_code
     *
     * @mbg.generated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.role_code
     *
     * @param roleCode the value for role_inf.role_code
     *
     * @mbg.generated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.role_name
     *
     * @return the value of role_inf.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.role_name
     *
     * @param roleName the value for role_inf.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.create_time
     *
     * @return the value of role_inf.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.create_time
     *
     * @param createTime the value for role_inf.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.creator
     *
     * @return the value of role_inf.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.creator
     *
     * @param creator the value for role_inf.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.update_time
     *
     * @return the value of role_inf.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.update_time
     *
     * @param updateTime the value for role_inf.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.reviser
     *
     * @return the value of role_inf.reviser
     *
     * @mbg.generated
     */
    public String getReviser() {
        return reviser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.reviser
     *
     * @param reviser the value for role_inf.reviser
     *
     * @mbg.generated
     */
    public void setReviser(String reviser) {
        this.reviser = reviser == null ? null : reviser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_inf.is_delete
     *
     * @return the value of role_inf.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_inf.is_delete
     *
     * @param isDelete the value for role_inf.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}