package com.queue.entity;

import java.io.Serializable;
import java.util.Date;

public class TedayWeather implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.T_ID
     *
     * @mbg.generated
     */
    private Long tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CRT_CITY
     *
     * @mbg.generated
     */
    private String crtCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CRT_DAY
     *
     * @mbg.generated
     */
    private String crtDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CRT_WEEK
     *
     * @mbg.generated
     */
    private String crtWeek;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CUR_LUNAR_DAY
     *
     * @mbg.generated
     */
    private String curLunarDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.PM_EXPONENT
     *
     * @mbg.generated
     */
    private Short pmExponent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    private Short temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CRT_WEATHER
     *
     * @mbg.generated
     */
    private String crtWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.TEDAY_TEMPERATURE
     *
     * @mbg.generated
     */
    private String tedayTemperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.TEDAY_WEATHER
     *
     * @mbg.generated
     */
    private String tedayWeather;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    private String windDirection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    private String tIdentity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teday_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teday_weather
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.T_ID
     *
     * @return the value of teday_weather.T_ID
     *
     * @mbg.generated
     */
    public Long gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.T_ID
     *
     * @param tId the value for teday_weather.T_ID
     *
     * @mbg.generated
     */
    public void settId(Long tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CRT_CITY
     *
     * @return the value of teday_weather.CRT_CITY
     *
     * @mbg.generated
     */
    public String getCrtCity() {
        return crtCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CRT_CITY
     *
     * @param crtCity the value for teday_weather.CRT_CITY
     *
     * @mbg.generated
     */
    public void setCrtCity(String crtCity) {
        this.crtCity = crtCity == null ? null : crtCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CRT_DAY
     *
     * @return the value of teday_weather.CRT_DAY
     *
     * @mbg.generated
     */
    public String getCrtDay() {
        return crtDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CRT_DAY
     *
     * @param crtDay the value for teday_weather.CRT_DAY
     *
     * @mbg.generated
     */
    public void setCrtDay(String crtDay) {
        this.crtDay = crtDay == null ? null : crtDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CRT_WEEK
     *
     * @return the value of teday_weather.CRT_WEEK
     *
     * @mbg.generated
     */
    public String getCrtWeek() {
        return crtWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CRT_WEEK
     *
     * @param crtWeek the value for teday_weather.CRT_WEEK
     *
     * @mbg.generated
     */
    public void setCrtWeek(String crtWeek) {
        this.crtWeek = crtWeek == null ? null : crtWeek.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CUR_LUNAR_DAY
     *
     * @return the value of teday_weather.CUR_LUNAR_DAY
     *
     * @mbg.generated
     */
    public String getCurLunarDay() {
        return curLunarDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CUR_LUNAR_DAY
     *
     * @param curLunarDay the value for teday_weather.CUR_LUNAR_DAY
     *
     * @mbg.generated
     */
    public void setCurLunarDay(String curLunarDay) {
        this.curLunarDay = curLunarDay == null ? null : curLunarDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.PM_EXPONENT
     *
     * @return the value of teday_weather.PM_EXPONENT
     *
     * @mbg.generated
     */
    public Short getPmExponent() {
        return pmExponent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.PM_EXPONENT
     *
     * @param pmExponent the value for teday_weather.PM_EXPONENT
     *
     * @mbg.generated
     */
    public void setPmExponent(Short pmExponent) {
        this.pmExponent = pmExponent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.TEMPERATURE
     *
     * @return the value of teday_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    public Short getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.TEMPERATURE
     *
     * @param temperature the value for teday_weather.TEMPERATURE
     *
     * @mbg.generated
     */
    public void setTemperature(Short temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CRT_WEATHER
     *
     * @return the value of teday_weather.CRT_WEATHER
     *
     * @mbg.generated
     */
    public String getCrtWeather() {
        return crtWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CRT_WEATHER
     *
     * @param crtWeather the value for teday_weather.CRT_WEATHER
     *
     * @mbg.generated
     */
    public void setCrtWeather(String crtWeather) {
        this.crtWeather = crtWeather == null ? null : crtWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.TEDAY_TEMPERATURE
     *
     * @return the value of teday_weather.TEDAY_TEMPERATURE
     *
     * @mbg.generated
     */
    public String getTedayTemperature() {
        return tedayTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.TEDAY_TEMPERATURE
     *
     * @param tedayTemperature the value for teday_weather.TEDAY_TEMPERATURE
     *
     * @mbg.generated
     */
    public void setTedayTemperature(String tedayTemperature) {
        this.tedayTemperature = tedayTemperature == null ? null : tedayTemperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.TEDAY_WEATHER
     *
     * @return the value of teday_weather.TEDAY_WEATHER
     *
     * @mbg.generated
     */
    public String getTedayWeather() {
        return tedayWeather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.TEDAY_WEATHER
     *
     * @param tedayWeather the value for teday_weather.TEDAY_WEATHER
     *
     * @mbg.generated
     */
    public void setTedayWeather(String tedayWeather) {
        this.tedayWeather = tedayWeather == null ? null : tedayWeather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.WIND_DIRECTION
     *
     * @return the value of teday_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    public String getWindDirection() {
        return windDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.WIND_DIRECTION
     *
     * @param windDirection the value for teday_weather.WIND_DIRECTION
     *
     * @mbg.generated
     */
    public void setWindDirection(String windDirection) {
        this.windDirection = windDirection == null ? null : windDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.T_IDENTITY
     *
     * @return the value of teday_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    public String gettIdentity() {
        return tIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.T_IDENTITY
     *
     * @param tIdentity the value for teday_weather.T_IDENTITY
     *
     * @mbg.generated
     */
    public void settIdentity(String tIdentity) {
        this.tIdentity = tIdentity == null ? null : tIdentity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teday_weather.CREATE_TIME
     *
     * @return the value of teday_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teday_weather.CREATE_TIME
     *
     * @param createTime the value for teday_weather.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}