package com.queue.entity;

import java.io.Serializable;

public class WeatherCity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEATHER_CITY.IDENTITY
     *
     * @mbg.generated
     */
    private Long identity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEATHER_CITY.CITY_ID
     *
     * @mbg.generated
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEATHER_CITY.CITY_NAME
     *
     * @mbg.generated
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEATHER_CITY.CITY_STATUS
     *
     * @mbg.generated
     */
    private Short cityStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WEATHER_CITY.DEL_STATUS
     *
     * @mbg.generated
     */
    private Short delStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table WEATHER_CITY
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEATHER_CITY.IDENTITY
     *
     * @return the value of WEATHER_CITY.IDENTITY
     *
     * @mbg.generated
     */
    public Long getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEATHER_CITY.IDENTITY
     *
     * @param identity the value for WEATHER_CITY.IDENTITY
     *
     * @mbg.generated
     */
    public void setIdentity(Long identity) {
        this.identity = identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEATHER_CITY.CITY_ID
     *
     * @return the value of WEATHER_CITY.CITY_ID
     *
     * @mbg.generated
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEATHER_CITY.CITY_ID
     *
     * @param cityId the value for WEATHER_CITY.CITY_ID
     *
     * @mbg.generated
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEATHER_CITY.CITY_NAME
     *
     * @return the value of WEATHER_CITY.CITY_NAME
     *
     * @mbg.generated
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEATHER_CITY.CITY_NAME
     *
     * @param cityName the value for WEATHER_CITY.CITY_NAME
     *
     * @mbg.generated
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEATHER_CITY.CITY_STATUS
     *
     * @return the value of WEATHER_CITY.CITY_STATUS
     *
     * @mbg.generated
     */
    public Short getCityStatus() {
        return cityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEATHER_CITY.CITY_STATUS
     *
     * @param cityStatus the value for WEATHER_CITY.CITY_STATUS
     *
     * @mbg.generated
     */
    public void setCityStatus(Short cityStatus) {
        this.cityStatus = cityStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WEATHER_CITY.DEL_STATUS
     *
     * @return the value of WEATHER_CITY.DEL_STATUS
     *
     * @mbg.generated
     */
    public Short getDelStatus() {
        return delStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WEATHER_CITY.DEL_STATUS
     *
     * @param delStatus the value for WEATHER_CITY.DEL_STATUS
     *
     * @mbg.generated
     */
    public void setDelStatus(Short delStatus) {
        this.delStatus = delStatus;
    }
}